<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>disable</ImplicitUsings>

		<Authors>RafaelEstevam.Nest</Authors>
		<Company>RafaelEstevam.Net</Company>
		<Product>Simple C# personal finance manager</Product>
		<Description>Simple C# personal finance manager</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/RafaelEstevamReis/SimpleFinance</PackageProjectUrl>
		<RepositoryUrl>https://github.com/RafaelEstevamReis/SimpleFinance</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>Simple API Finance Manager</PackageTags>
		<PackageReleaseNotes>See examples and documentation on the GitHub page https://github.com/RafaelEstevamReis/SimpleFinance</PackageReleaseNotes>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<!-- ============================================================ -->
		<!-- Nome e versão do assembly -->
		<!-- ============================================================ -->
		<AssemblyName>MyPersonalFinances</AssemblyName>
		<AssemblyVersion>1.1.0</AssemblyVersion>
		<Version>$(AssemblyVersion)</Version>
		<FileVersion>$(AssemblyVersion)</FileVersion>
		
		<!-- ============================================================ -->
		<!-- Single file content -->
		<!-- ============================================================ -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>false</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishReadyToRun>true</PublishReadyToRun>
		<PublishTrimmed>false</PublishTrimmed>
		<ApplicationIcon>Assets\icon.ico</ApplicationIcon>

	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Reports\CategoriesOverview.rdlc" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Assets\icon.ico" />
	  <Content Include="Reports\CategoriesOverview.rdlc">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ReportViewerCore.NETCore" Version="15.1.33" />
		<PackageReference Include="ReportViewerCore.WinForms" Version="15.1.33" />
		<PackageReference Include="Simple.API" Version="1.10.0" />
		<PackageReference Include="Simple.BotUtils" Version="1.8.14" />
		<PackageReference Include="WinForms.DataVisualization" Version="1.10.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Simple.Finance\Simple.Finance.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Reports\YearlySummary.rdlc">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>