<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" id="ReportItemSchemas" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CategoriesOverviewModel" nillable="true" type="CategoriesOverviewModel" />
  <xs:complexType name="CategoriesOverviewModel">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="CategoryName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Description" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="Value" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Date" type="xs:dateTime" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="YearlySummaryModel" nillable="true" type="YearlySummaryModel" />
  <xs:complexType name="YearlySummaryModel">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="CategoryName" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month01" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month02" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month03" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month04" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month05" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month06" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month07" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month08" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month09" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month10" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month11" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="Month12" type="xs:decimal" />
      <xs:element minOccurs="1" maxOccurs="1" name="RowTotal" type="xs:decimal" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>